# Generated by Django 6.0.5 on 2026-05-27 12:41

from django.db import migrations


def create_managers_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    manager_group, created = Group.objects.get_or_create(name="Managers")

    codenames = [
        "add_project",
        "change_project",
        "delete_project",
        "add_task",
        "change_task",
        "delete_task",
        "add_position",
        "add_tasktype",
    ]

    permissions = Permission.objects.filter(codename__in=codenames)

    manager_group.permissions.set(permissions)


def remove_managers_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Managers").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0004_project_task_project"),
    ]

    operations = [
        migrations.RunPython(create_managers_group, reverse_code=remove_managers_group),
    ]
